### ISSUE TITLE
使用tensorflow时，如何使用自己的图像数据集训练

### ISSUE THREAD

**Issue by xuewenyuan** [zylhub/TensorFlow-Demo#1]
Hi，请问，在这一句中https://github.com/sherlockzoom/TensorFlow-Demo/blob/master/cnn_tf.py#L89  
train.csv文件中存放的是图像的路径及其标签吗？

**Comment by zylhub** [comment]
`train.csv`文件应该是预处理好的数值型的灰度值和类标，这里的代码是以mnist数据为例来做的。如果只是跑实验，建议使用http://keras.io/ 可以快速构建你的模型，当然前提是你的数据预处理没有问题(http://keras.io/datasets/  具体格式可以参考这里)
